### ISSUE TITLE
[BUG] no_service error

### ISSUE THREAD

**Issue by manuelmeurer** [arddluma/cloudflare-pages-slack-notification#11]
**Describe the bug**

The action properly waits until the CF Pages build finishes but then shows "no_service".

**GitHub Action yml config**
```
name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Await Cloudflare Pages build and send Slack notification
        uses: arddluma/cloudflare-pages-slack-notification@v2.5
        with:
          accountEmail: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project: uplink-docs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          slackWebHook: ${{ secrets.SLACK_WEBHOOK_URL }}
```

**Expected behavior**
A success message

**Screenshots**
![add github action to notify via slack · uplinkhq:docs@cc732a6 2023-01-26 13-57-08](https://user-images.githubusercontent.com/16672/214841659-98d1d4c6-cbe7-4e04-b3be-f60e02325b79.png)
