### ISSUE TITLE
Always throwing error when lastState = "build"

### ISSUE THREAD

**Issue by adheegm** [arddluma/cloudflare-pages-slack-notification#2]
Hello @arddluma - Great work on you CF pages slack notification action

I found an issue when using the action - Its throwing error everytime when the last state is `build` and it is never been success.

Here's the configurations on my `yml` file

```
trigger-slack-notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps:      
      - name: Await CF Pages and send Slack notification
        uses: arddluma/cloudflare-pages-slack-notification@v2
        with:
          accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
          apiKey: ${{ secrets.CF_API_KEY  }}
          accountId: ${{ secrets.CF_ACC_ID  }}
          project: ${{ secrets.CF_PAGES_PROJECT  }}
          slackWebHook: ${{ secrets.SLACK_WEBHOOK_URL  }}
```

Is there anything that I missed on the configuration? Is this something that you noticed?
