### ISSUE TITLE
[BUG] Skipped Deployment Runs Indefinitely

### ISSUE THREAD

**Issue by logan-jobzmall** [arddluma/cloudflare-pages-slack-notification#9]
**Describe the bug**
When a deployment is "skipped" by cloudflare, the action continuously runs indefinitely.

**GitHub Action yml config**
```
name: Send Slack notifications
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send Slack deployment notifications
      uses: arddluma/cloudflare-pages-slack-notification@v2.2
      with:
        accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
        apiKey: ${{ secrets.CF_API_KEY  }}
        accountId: ${{ secrets.CF_ACC_ID  }}
        project: ${{ secrets.CF_PROJECT  }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        slackWebHook: ${{ secrets.SLACK_WEBHOOK  }}
```

**Expected behavior**
I would expect the action step to be cancelled.
